default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_test

production:
  <<: *default
  database: hosting_image_upload_1208_production
  username: hosting_image_upload_1208
  password: <%= ENV["HOSTING_IMAGE_UPLOAD_1208_DATABASE_PASSWORD"] %>
